
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: unsaved
* name: accumulator_fill
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include <stdint.h>



static const uint8_t image_data_accumulator_fill[32] = {
    // ███████∙∙
    // ███████∙∙
    // ███████∙∙
    // ██████∙∙∙
    // ██████∙∙∙
    // ██████∙∙∙
    // █████████
    // █████████
    // ████████∙
    // ∙██████∙∙
    // ∙██████∙∙
    // ∙█████∙∙∙
    // ∙████∙∙∙∙
    // ∙███∙∙∙∙∙
    // ███∙∙∙∙∙∙
    // ███∙∙∙∙∙∙
    0xfe, 0x00, 
    0xfe, 0x00, 
    0xfe, 0x00, 
    0xfc, 0x00, 
    0xfc, 0x00, 
    0xfc, 0x00, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x00, 
    0x7e, 0x00, 
    0x7e, 0x00, 
    0x7c, 0x00, 
    0x78, 0x00, 
    0x70, 0x00, 
    0xe0, 0x00, 
    0xe0, 0x00
};
const tImage accumulator_fill = { image_data_accumulator_fill, 9, 16,
    8 };

