
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: unsaved
* name: temp_fill
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include <stdint.h>



static const uint8_t image_data_temp_fill[56] = {
    // ∙∙∙█████∙∙∙
    // ∙∙∙█████∙∙∙
    // ∙∙∙█████∙∙∙
    // ∙∙∙█████∙∙∙
    // ∙∙∙███████∙
    // ∙∙∙███████∙
    // ∙∙∙█████∙∙∙
    // ∙∙∙█████∙∙∙
    // ∙∙∙███████∙
    // ∙∙∙███████∙
    // ∙∙∙███████∙
    // ∙∙∙█████∙∙∙
    // ∙∙∙█████∙∙∙
    // ∙∙∙███████∙
    // ∙∙∙███████∙
    // ∙∙∙█████∙∙∙
    // ∙∙∙█████∙∙∙
    // ∙∙███████∙∙
    // ∙█████████∙
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ∙█████████∙
    // ∙∙███████∙∙
    0x1f, 0x00, 
    0x1f, 0x00, 
    0x1f, 0x00, 
    0x1f, 0x00, 
    0x1f, 0xc0, 
    0x1f, 0xc0, 
    0x1f, 0x00, 
    0x1f, 0x00, 
    0x1f, 0xc0, 
    0x1f, 0xc0, 
    0x1f, 0xc0, 
    0x1f, 0x00, 
    0x1f, 0x00, 
    0x1f, 0xc0, 
    0x1f, 0xc0, 
    0x1f, 0x00, 
    0x1f, 0x00, 
    0x3f, 0x80, 
    0x7f, 0xc0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0x7f, 0xc0, 
    0x3f, 0x80
};
const tImage temp_fill = { image_data_temp_fill, 11, 28,
    8 };

